# Generated by Django 3.0 on 2019-12-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
